version: '2'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - se_backend
    volumes:
      - ./nginx/www:/var/www/nginx

  hbase:
    build: ./hbase
    ports:
      - "8080:8080"
    networks:
      se_backend:
        aliases:
          - zookeeper

  grproxy:
    build: ./grproxy
    ports: 
      - "3000:3000"
    networks:
      - se_backend
      - se_frontend

  gserve1:
    build: ./gserve
    environment:
      - version=gserve1
    depends_on:
      - hbase
      - grproxy
    ports: 
      - "7000:7000"
    networks:
      - se_backend

  gserve2:
    build: ./gserve
    environment:
      - version=gserve2
    depends_on:
      - hbase
      - grproxy
    ports: 
      - "7001:7000"
    networks:
      - se_backend

networks:
  se_backend:
  se_frontend: